* 安装ubuntu系统 && git 环境安装

** yong快捷键使用
一键切换到 输入法  ctrl_`
注意删除 不使用的输入法会更快
/root/.yong/yong.ini 这个是缓存文件 修改/usr/local/yong/路径下的文件不
起作用的

** fbterm 搜狗输入法安装？

** ubuntu 亮度调节方法
sudo vim /etc/rc.local

[Center]

5 我们许在exit 0 前面增加一句命令即可：

echo 109 > /sys/class/backlight/intel_backlight/brightness

以后开机即可会设置亮度为109.

** ubuntu 无线网络开关设置
ifdown
ifup

** yong tty
  ** yong拼音输入法搞定了，尝试了下还可以，这下可以强制不上网页了，专注文字
  ** 之前没有安装成功，理由是安装在32位，安装64位就可以了

三：下载并安装小小拼音输入法(yong),由于该软件在Linux下只提供7z压缩
包文件,所以需下载并安装p7zip工具包.
(1). 安装p7zip:
下载地址:
http://sourceforge.net/projects/p7zip/files/p7zip/9.20.1/p7zip_9.20.1_src_all.tar.bz2/download

make 7z
sudo ./install.sh

(2). 下载并解压yong:
下载地址:http://u.115.com/file/bh1ojcho

解压：
7z x yong-lin-1.7.0-1.7z

(3). 安装：
sudo mv yong /usr/local
cd /usr/local/yong
sudo ./yong-tool.sh --install

(4). 修改配置文件"~/.yong/yong.ini",修改默认输入法为pinyin:

[IM]
default=6
中英文切换键改为左SHIFT:
[key]
CNen=LSHIFT

四：接着,修改fbterm的配置文件"~/.fbtermrc",使fbterm使用yong作为
其默认的输入法:



input-method=yong
免费下载地址在 http://linux.linuxidc.com/             升启动                                
                                                    * Apache Tomcat 8.0.32 发布下载         
用户名与密码都是www.linuxidc.com                    * Gitlab 8.4.4 发布下载，Git 代码托管平 
                                                      台                                    
具体下载目录在 /pub/小小输入法(yong输入法)/                                                 
                                                                                            
使用方法：                                                                                  
                                                                                            
安装：                                                                                      
进安装目录，执行命令                                                                        
sudo ./yong-tool.sh –install                                                                
                                                                                            
卸载：                                                                                      
sudo ./yong-tool.sh –uninstall                    本周热门                                  
                                                                                            
选择作为默认输入法：                                                                        
./yong-tool.sh –select                                                                      
                                                    * Linux公社下载FTP资源的请到FTP服务中心 
具体事项你可以参考压缩包里面的yong.chm，当然你先      激活会                                
要安装一个chm阅读器如chmsee                         * 免费才最贵：揭露「免费」Windows 10 的 
sudo apt-get install chmsee                           真实成                                


** w3m显示乱码问题处理
安装完字符集后，访问百度网址正常
http://www.linuxidc.com/Linux/2014-02/96939.htm

中文输入
http://blog.csdn.net/flywindmouse/article/details/13527769

http://www.guokr.com/blog/749084/
http://rutine.blog.163.com/blog/static/7908087220144155448206/
http://www.linuxidc.com/Linux/2015-01/111975.htm

** arclinux got
http://jingyan.baidu.com/article/59a015e3a9170ef7948865f3.html

** 安装中文语言包
sudo apt-get install language-pack-zh-hans
** 无线驱动无法使用 安装的两种方法：
1. 连接网络 直到重启安装无线驱动结束
2. 安装mint驱动程序
Mint Driver Manager 
http://www.linuxidc.com/Linux/2014-05/102128.htm

注意：搜索中文名，驱动管理才能找到！

** 必装软件
emacs 强大的不用我讲了
emacs +w3m  网页也可以文本编辑
chromium 浏览器非常好用

** telnet 乱码
local 是 utf-8 的时候 telnet gbk编码的bbs 会出现乱码

解决方法 : 使用 luit
luit -encoding gbk telnet bbs.tsinghua.edu.cn 
** emacs 插件

yasnippets：  snippets c++ java
jdee：       自动导入jar包  集成编译和运行 调试
这个装起来比较笨重 不好用
emacs 字体： 家里的输入法字体换爽 公司的字体很差，可以考虑下如何修改

** git环境安装

*** github 集成
*** github 提交 rateyu@gmail.com


github

1. 在本地建立一个文件夹，然后做一些全局变量的初始化
git config --global user.name = "用户名或者用户ID"
git config --global user.email = "邮箱"
这两个选项会在以后的使用过程中自动添加到代码中。

2. 创建验证用的公钥
这个是比较复杂和困扰大多数人的地方，因为 git 是通过 ssh 的方式访问资源库的，所以需要在本地创建验证用的文件。
使用命令：ssh-keygen -C 'you email address@gmail.com' -t rsa
会在用户目录 ~/.ssh/ 下建立相应的密钥文件
可以使用 ssh -v git@github.com 命令来测试链接是否畅通
3. 上传公钥
在 github.com 的界面中 选择右上角的 Account Settings，然后选择 SSH Public Keys ，选择新加。
Title 可以随便命名，Key 的内容拷贝自 ~/.ssh/id_rsa.pub 中的内容，完成后，可以再使用 ssh -v git@github.com 进行测试。看到下面的信息表示验证成功。

- 注意：此处要重启os，比较奇怪
- emacs -nw  不使用x11界面

4. 复制代码

使用 git clone git@github.com:cocowool/userguide.git userguide 可以将代码复制到本地的 userguide 文件夹中

git clone git@github.com:rateyu/rateyu.github.io.git ./blog2015
此种方式有读写权限

> 运行命令$git clone https://github.com/jenkinsci/gerrit-trigger-plugin.git
> 此种方式只有读的权限

sublime txt 3 github使用说明
安装 包管理器
git quick commit
git push current branch


5. 提交流程
1) git add .
2) git commit -m "ubuntu 14 环境安装"

*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

3) 提交远程代码
git push -u origin master

其他相关命令参考：

进行自己的修改，完成后请求原作者合并
git pull person master 

# 创建一个版本库
git init
# 每次修改好了后，可以先将修改存入stage(快照/索引)中
git add <modified files>
# 修改了大量文件则使用下面这个命令批量存入
git add .
# 使用commit将快照/索引中的内容提交到版本库中
git commit -m "msg"
# 也可以将git add与git commit用一个指令完成
git commit -a -m "msg"
# 将本地的git档案与github(远程)上的同步
git push
# 将github(远程)的git档案与本地的同步(即更新本地端的repo)
git pull
# 例如,pull指令其实包含了fetch(將变更复制回來)以及merge(合并)操作
git pull git://github.com/tom/test.git
 
# 另外版本控制系統的branch功能也很有意思，若同时修改bug，又要加入新功能，可以fork出一个branch：一个专门修bug，一个专门加入新功能，等到稳定后再merge合并
git branch bug_fix # 建立branch，名为bug_fix
git checkout bug_fix # 切换到bug_fix
git checkout master #切换到主要的repo
git merge bug_fix #把bug_fix这个branch和现在的branch合并
 
# 若有remote的branch，想要查看并checkout
git branch -r # 查看远程branch
git checkout -b bug_fix_local bug_fix_remote #把本地端切换为远程的bug_fix_remote branch并命名为bug_fix_local
 
# 还有其它可以查看repo状态的工具
git log #可以查看每次commit的改变
git diff #可以查看最近一次改变的內容，加上参数可以看其它的改变并互相比较
git show #可以看某次的变更
 
# 若想知道目前工作树的状态，可以輸入
git status


参考url地址：
http://www.cnblogs.com/cocowool/archive/2010/10/19/1855616.html
** ubuntu 14 访问win7 
Ubuntu14.04 远程连接Win7 报错：无法连接到RDP服务器

ym@ym-HP430G2:~$ cd .freerdp/
ym@ym-HP430G2:~/.freerdp$ ls
certs  known_hosts
ym@ym-HP430G2:~/.freerdp$ rm -rf known_hosts 
ym@ym-HP430G2:~/.freerdp$ ls
certs
ym@ym-HP430G2:~/.freerdp$ swkey 
ym@ym-HP430G2:~/.freerdp$ 

** ubuntu 访问win7
rdp 方式访问
用户名密码
还有域名
http://www.th7.cn/system/lin/201410/72661.shtml
