* 安装ubuntu系统 && git 环境安装
** android studio 开发登陆模块完成
自动生成的程序
如何发布版本 gradle
gradle 多渠道打包功能
http://www.cnblogs.com/xgjblog/p/5461245.html

** android studio 2
ide生成登陆界面
编写登录界面

http://www.server110.com/kvm/201401/4879.html
kvm not found

** apache 配置文件
http://blog.chinaunix.net/uid-21807675-id-1814871.html
** ubuntu 修改文件夹用户组
chown -P ym:ym folder

** ubuntu命令行操作
  进入fbterm模式
  进入ym用户
  敲emacs 进入编辑环境
  进入码字大模式！！
** win 10 安装sshd cygwin
咖啡厅 等公网防火墙关闭
参考 url地址  注意，no选项
http://www.cnblogs.com/tippoint/archive/2012/10/18/2729078.html


** win 10 tomcat serv
   SCHEDULED: <2016-04-24 日>
http://tomcat.apache.org/tomcat-8.0-doc/windows-service-howto.html#Installing_services

http://www.cnblogs.com/tippoint/archive/2012/10/18/2729078.html
C:\Program Files \(x86\)\VMware\VMware Workstation\vmrun.exe start "D:\vm-linux\suse11\SUSE Linux Enterprise 11.vmx"


/cygdrive/c/Program Files (x86)/VMware/VMware Workstation/vmrun.exe
stop  "/cygdrive/d/vm-linux/suse11/SUSE Linux Enterprise 11.vmx"

vmrun start "D:\vm-linux\suse13\SUSE Linux Enterprise 13.vmx"

vmrun start "D:\vm-linux\ubuntu-zeromq\Ubuntu 64-bit 129 zeromq-python-nodejs.vmx"

vmrun start "D:\vm-linux\ubuntu-mq\Ubuntu 64-bit 124 mq.vmx"

windows 关机命令
shutdown -s -t 3

开发个程序控制 windows 10 机器上的虚拟机
** nmap 探测主机
http://blog.chinaunix.net/uid-25885064-id-3483813.html
服务和端口
nmap -PS 192.168.1.234　
nmap -sP 192.168.1.0/24

用nmap对局域网扫描一遍，然后查看arp缓存表就可以知道局域内ip对应的mac了。
nmap比较强大也可以直接扫描mac地址和端口。执行扫描之后就可以 cat
/proc/net/arp查看arp缓存表了

ym@ym-HP430G2:~$ cat /proc/net/arp
IP address       HW type     Flags       HW address            Mask     Device
192.168.1.15     0x1         0x2         1c:e6:2b:e2:82:b1     *        wlan0
192.168.1.119    0x1         0x2         9c:21:6a:05:1d:fe     *        wlan0
192.168.1.16     0x1         0x2         00:1f:d0:28:a3:3a     *        wlan0
192.168.1.100    0x1         0x2         70:73:cb:23:ec:61     *        wlan0
192.168.1.1      0x1         0x2         00:27:19:4e:e7:76     *        wlan0
192.168.1.66     0x1         0x2         00:1f:3b:c9:68:59     *        wlan0
192.168.1.18     0x1         0x2         74:d4:35:19:a0:9c     *        wlan0
192.168.1.2      0x1         0x2         58:44:98:b8:5b:6f     *        wlan0
192.168.1.10     0x1         0x2         00:18:de:80:14:3b     *        wlan0
192.168.1.4      0x1         0x2         74:51:ba:fb:cd:1b     *        wlan0


** ubuntu 挂载硬盘

查看分区 sudo blkdi
重要命令      lsblk
sudo parted /dev/sde print
http://www.169it.com/article/3218336418.html

   buntu自动挂载硬盘方法
首先建立挂载目录
例如：
sudo mkdir /movie #根目录下建立movie文件夹
sudo mkdir /work   #根目录下建立work文件夹

然后查看硬盘信息
sudo fdisk -l

Disk /dev/sda: 500.1 GB, 500107862016 bytes
255 heads, 63 sectors/track, 60801 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Disk identifier: 0x6fd074d4

   Device Boot      Start         End      Blocks   Id System
/dev/sda1   *           1        3251    26113626    7 HPFS/NTFS
/dev/sda2            3252       48177   360868095    f W95 Ext'd (LBA)
/dev/sda3           48178       60801   101402280   83 Linux
/dev/sda5            3252        8414    41471766    7 HPFS/NTFS
/dev/sda6            8415       21800   107523013+   7 HPFS/NTFS
/dev/sda7           21801       47934   209921323+   7 HPFS/NTFS
/dev/sda8           47935       48177     1951866   82 Linux swap / Solaris

Disk /dev/sdb: 320.0 GB, 320072933376 bytes
255 heads, 63 sectors/track, 38913 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes
Disk identifier: 0x4fd353d4

   Device Boot      Start         End      Blocks   Id System
/dev/sdb1               1       12876   103425446    7 HPFS/NTFS
/dev/sdb2           12876       38914   209151681    7 HPFS/NTFS

这里要把sda7 sdb2自动挂载在work和movie下

修改fstab文件
sudo vim /etc/fstab

sw              0       0
/dev/scd0       /media/cdrom0   udf,iso9660 user,noauto,exec,utf8 0       0
/dev/fd0        /media/floppy0 auto    rw,user,noauto,exec,utf8 0       0
/dev/sda6       /doc            auto                             0        0
/dev/sdb1       /xp             auto                             0        0
/dev/sda7       /work           auto                             0       0
/dev/sdb2       /movie          auto                             0       0

加黑是手动加入的
保存退出重新启动就ok了

** ubuntu 非ｒｏｏｔ关机　不输入密码
进入终端，执行sudo visudo

在#User privilege specification下面会罗列一些规则，我们现在需要做的是对我们的用户进行一些操作。假如我们的用户名为nenew

在文件的最后一行添加：


   在#User privilege specification下面会罗列一些规则，我们现在需要做的是对我们的用户进行一些操作。假如我们的用户名为nenew

在文件的最后一行添加：

nenew    ALL=(ALL) NOPASSWD: ALL

然后保存退出，执行

sudo usermod -aG admin nenew

重启下看看nenew帐号执行sudo还需要密码么？这里我们需要了解顺序这个问题，在ubuntu的wiki上有比较详细的介绍。

%admin ALL=(ALL) ALL
这行只是让admin组的用户拥有可以像任何帐号一样执行命令的能力，但是还是需要有密码的，因此我们需要把我们的nenew用户加入到admin组中，所以有sudo usermod
-aG admin nenew ，然后是对其进行NOPASSWD定义，这行一定要在%admin ALL=(ALL) ALL 这行后面，才会生效。

文章发玩之后很多朋友提出不安全问题来，确实，这样是存在安全隐患的。奶牛此文的目的也只是想让各位了解下sudoers的那个生效的顺序，当然，我们可以把最后的

nenew    ALL=(ALL) NOPASSWD: ALL 更改为对于命令进行限制，例如对于关机命令取消密码

nenew    ALL=(ALL) NOPASSWS: /sbin/shutdown, /sbin/halt, /sbin/reboot

更详细的说明请看:

https://help.ubuntu.com/community/Sudoers

http://www.gratisoft.us/sudo/sudoers.man.html

注意：如果你添加了一行在root的下面，这样的话修改是不会生效的，因为%admin ALL=(ALL) ALL这行的策略会覆盖掉nenew的这条策略，又变成需要密码，所以你可以
把nenew这句话搬到admin这句话的后面，立马生效。

** ubuntu suse zsh oh autojump && fish 安装与使用；脚本灰常好用
   autojump <--> fish popd pushd dirs 

** fish 设置
当然如果你实在想配置，输入 fish_config 命令会启动 web 管理界面。

什么？逼格太低，非要手动配置。OK， ~/.config/fish/config.fish这就是 fish 的配置文件，类似于 bash 的.bashrc。

我喜欢配置三件东西：

1.问候语（配置config.fish）：


复制代码
代码如下:
set fish_greeting 'Talk is cheap. Show me the code.'

2.命令行提示（在web界面配置，完成后会生成~/.config/fish/functions/fish_prompt.fish）：

http://www.jb51.net/LINUXjishu/408682.html


** ubuntu 修改端口和密码
/etc/ssh/sshd_config
1. 修改 root 密码
sudo passwd root
[root@localhost /]#service ssh restart

** emacs - w3m 重新安装 太难用了
每次都对 c_c c_k
重新再装一遍
** grub配置 命令行模式启动
   emacs /etc/default/grub
   千万注意 需要更新  update-grub2
   否则无效
** fbterm 搜狗输入法安装？
** yong快捷键使用
一键切换到 输入法  ctrl_`
注意删除 不使用的输入法会更快
/root/.yong/yong.ini 这个是缓存文件 修改/usr/local/yong/路径下的文件不
起作用的

** ubuntu 亮度调节方法

Ubuntu / Debian 系统有一个通病，那就是每次开机，系统都会把你的屏幕亮度调到最大值。 我很惊讶为什么到了14.04版本这个问题还是没有修复。 不过我们可以通过脚本让Ubuntu每次启动时都把亮度设置成一个固定的值。

首先查看一下你的屏幕亮度值的范围：

sudo cat /sys/class/backlight/acpi_video0/max_brightness

我的是15，也就是说亮度值可以在 0 ~ 15之间。

修改 /etc/rc.local ,在最后的 exit 0 之前添加：

echo 3 > /sys/class/backlight/acpi_video0/brightness

系统完成启动最后会执行这个脚本，因此每次开机，都会把亮度值设置成3


** 查卡主机最大亮度
1 查看自己的系统亮度的最大值：

cd /sys/class/backlight

[Center]

（笔记本的显卡型号不同->亮度调节文件夹名会不同）。

2 我的是intel_backlight

cd intel_backlight

[Center]

3 来到这里，你肯定知道：max_brightness 系统可以调节的最大亮度值。
bightness就是你正使用的亮度值了。

cat max_brightness

cat brightness


** ubuntu 无线网络开关设置
ifconfig wlan0 down
ifconfig wlan0 up   

** yong tty
  ** yong拼音输入法搞定了，尝试了下还可以，这下可以强制不上网页了，专注文字
  ** 之前没有安装成功，理由是安装在32位，安装64位就可以了

三：下载并安装小小拼音输入法(yong),由于该软件在Linux下只提供7z压缩
包文件,所以需下载并安装p7zip工具包.
(1). 安装p7zip:
下载地址:
http://sourceforge.net/projects/p7zip/files/p7zip/9.20.1/p7zip_9.20.1_src_all.tar.bz2/download

make 7z
sudo ./install.sh

(2). 下载并解压yong:
下载地址:http://u.115.com/file/bh1ojcho

解压：
7z x yong-lin-1.7.0-1.7z

(3). 安装：
sudo mv yong /usr/local
cd /usr/local/yong
sudo ./yong-tool.sh --install

(4). 修改配置文件"~/.yong/yong.ini",修改默认输入法为pinyin:

[IM]
default=6
中英文切换键改为左SHIFT:
[key]
CNen=LSHIFT

四：接着,修改fbterm的配置文件"~/.fbtermrc",使fbterm使用yong作为
其默认的输入法:



input-method=yong
免费下载地址在 http://linux.linuxidc.com/             升启动                                
                                                    * Apache Tomcat 8.0.32 发布下载         
用户名与密码都是www.linuxidc.com                    * Gitlab 8.4.4 发布下载，Git 代码托管平 
                                                      台                                    
具体下载目录在 /pub/小小输入法(yong输入法)/                                                 
                                                                                            
使用方法：                                                                                  
                                                                                            
安装：                                                                                      
进安装目录，执行命令                                                                        
sudo ./yong-tool.sh –install                                                                
                                                                                            
卸载：                                                                                      
sudo ./yong-tool.sh –uninstall                    本周热门                                  
                                                                                            
选择作为默认输入法：                                                                        
./yong-tool.sh –select                                                                      
                                                    * Linux公社下载FTP资源的请到FTP服务中心 
具体事项你可以参考压缩包里面的yong.chm，当然你先      激活会                                
要安装一个chm阅读器如chmsee                         * 免费才最贵：揭露「免费」Windows 10 的 
sudo apt-get install chmsee                           真实成                                


** w3m显示乱码问题处理
安装完字符集后，访问百度网址正常
http://www.linuxidc.com/Linux/2014-02/96939.htm

中文输入
http://blog.csdn.net/flywindmouse/article/details/13527769

http://www.guokr.com/blog/749084/
http://rutine.blog.163.com/blog/static/7908087220144155448206/
http://www.linuxidc.com/Linux/2015-01/111975.htm

** arclinux got
http://jingyan.baidu.com/article/59a015e3a9170ef7948865f3.html

** 安装中文语言包
sudo apt-get install language-pack-zh-hans
** 无线驱动无法使用 安装的两种方法：
1. 连接网络 直到重启安装无线驱动结束
2. 安装mint驱动程序
Mint Driver Manager 
http://www.linuxidc.com/Linux/2014-05/102128.htm

注意：搜索中文名，驱动管理才能找到！

** 必装软件
emacs 强大的不用我讲了
emacs +w3m  网页也可以文本编辑
chromium 浏览器非常好用

** telnet 乱码
local 是 utf-8 的时候 telnet gbk编码的bbs 会出现乱码

设置终端字符集为 gbk

解决方法 : 使用 luit
luit -encoding gbk telnet bbs.tsinghua.edu.cn 
** emacs 插件

yasnippets：  snippets c++ java
jdee：       自动导入jar包  集成编译和运行 调试
这个装起来比较笨重 不好用
emacs 字体： 家里的输入法字体换爽 公司的字体很差，可以考虑下如何修改

** git环境安装

*** github 集成
*** github 提交 rateyu@gmail.com


github

1. 在本地建立一个文件夹，然后做一些全局变量的初始化
git config --global user.name = "用户名或者用户ID"
git config --global user.email = "邮箱"
这两个选项会在以后的使用过程中自动添加到代码中。

2. 创建验证用的公钥
这个是比较复杂和困扰大多数人的地方，因为 git 是通过 ssh 的方式访问资源库的，所以需要在本地创建验证用的文件。
使用命令：ssh-keygen -C 'you email address@gmail.com' -t rsa
会在用户目录 ~/.ssh/ 下建立相应的密钥文件
可以使用 ssh -v git@github.com 命令来测试链接是否畅通
3. 上传公钥
在 github.com 的界面中 选择右上角的 Account Settings，然后选择 SSH Public Keys ，选择新加。
Title 可以随便命名，Key 的内容拷贝自 ~/.ssh/id_rsa.pub 中的内容，完成后，可以再使用 ssh -v git@github.com 进行测试。看到下面的信息表示验证成功。

- 注意：此处要重启os，比较奇怪
- emacs -nw  不使用x11界面

4. 复制代码

使用 git clone git@github.com:cocowool/userguide.git userguide 可以将代码复制到本地的 userguide 文件夹中

git clone git@github.com:rateyu/rateyu.github.io.git ./blog2015
此种方式有读写权限

> 运行命令$git clone https://github.com/jenkinsci/gerrit-trigger-plugin.git
> 此种方式只有读的权限

sublime txt 3 github使用说明
安装 包管理器
git quick commit
git push current branch


5. 提交流程
1) git add .
2) git commit -m "ubuntu 14 环境安装"

*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

3) 提交远程代码
git push -u origin master

其他相关命令参考：

进行自己的修改，完成后请求原作者合并
git pull person master 

# 创建一个版本库
git init
# 每次修改好了后，可以先将修改存入stage(快照/索引)中
git add <modified files>
# 修改了大量文件则使用下面这个命令批量存入
git add .
# 使用commit将快照/索引中的内容提交到版本库中
git commit -m "msg"
# 也可以将git add与git commit用一个指令完成
git commit -a -m "msg"
# 将本地的git档案与github(远程)上的同步
git push
# 将github(远程)的git档案与本地的同步(即更新本地端的repo)
git pull
# 例如,pull指令其实包含了fetch(將变更复制回來)以及merge(合并)操作
git pull git://github.com/tom/test.git
 
# 另外版本控制系統的branch功能也很有意思，若同时修改bug，又要加入新功能，可以fork出一个branch：一个专门修bug，一个专门加入新功能，等到稳定后再merge合并
git branch bug_fix # 建立branch，名为bug_fix
git checkout bug_fix # 切换到bug_fix
git checkout master #切换到主要的repo
git merge bug_fix #把bug_fix这个branch和现在的branch合并
 
# 若有remote的branch，想要查看并checkout
git branch -r # 查看远程branch
git checkout -b bug_fix_local bug_fix_remote #把本地端切换为远程的bug_fix_remote branch并命名为bug_fix_local
 
# 还有其它可以查看repo状态的工具
git log #可以查看每次commit的改变
git diff #可以查看最近一次改变的內容，加上参数可以看其它的改变并互相比较
git show #可以看某次的变更
 
# 若想知道目前工作树的状态，可以輸入
git status


参考url地址：
http://www.cnblogs.com/cocowool/archive/2010/10/19/1855616.html
** ubuntu 14 访问win7 
Ubuntu14.04 远程连接Win7 报错：无法连接到RDP服务器

ym@ym-HP430G2:~$ cd .freerdp/
ym@ym-HP430G2:~/.freerdp$ ls
certs  known_hosts
ym@ym-HP430G2:~/.freerdp$ rm -rf known_hosts 
ym@ym-HP430G2:~/.freerdp$ ls
certs
ym@ym-HP430G2:~/.freerdp$ swkey 
ym@ym-HP430G2:~/.freerdp$ 

** ubuntu 访问win7
rdp 方式访问
用户名密码
还有域名
http://www.th7.cn/system/lin/201410/72661.shtml


* 未解决的问题
** ubuntu shell fish
整理几个好用的 Ubuntu 工具(Sublime Text, Jupiter, Tweak, MyUnity,
Guake, Fish, dnsmasq)
Ubuntu完全教程，让你成为Ubuntu高手！
http://www.cnblogs.com/dutlei/archive/2012/11/20/2778327.html

sudo apt-get install fish

从bash进入fish直接输入fish就行了
安装好第一步是修改 OS 默认 shell：

复制代码代码如下:

chsh -s /usr/bin/fish
