*　2015 总结　２０１５年１２月１３日
** ubuntu jetbrain android

** ubuntu 安装虚拟android设备
http://blog.chinaunix.net/uid-25885064-id-3354792.html
  
** jetbrain 创建android工程
http://blog.csdn.net/kiwi_coder/article/details/8041360
需要安装三个  sdk tools/sdk platform-tools/android平台 

** 增加安装两个包:
error android apt compiler cannot run program aapt
试试这个包lib32z1-dev 使用此包问题解决
lib32stdc++6

** 下一步如何使用里面的控件　以及如何串联一个项目？？
** 学习jetbrain 教程

gridview使用
   http://blog.csdn.net/leichelle/article/details/7951290

GitHub上最火的40个Android开源项目
http://www.open-open.com/lib/view/open1388317199516.html

http://blog.csdn.net/liang5630/article/details/37723455

** 关于颜小君的季度问题

*** 维护工作，质量较低
季度中的事情
做好如下事情，可以进一步提高日常的维护工作：

关于Ocean维护的事情，我是这样看的，有些地方也吐吐苦水：
个人觉得，这里包括很多问题，需要一个系统的方式解决此问题，比如：

目前主要做一些Ocean维护相关的工作，

问题和看法：
环境问题：
　　开发站：责任人，最近一次升级的人负责开发站应用正常，
升级问题：

主站问题：

项目问题：

个人提升问题：

技术等级问题：



１　主站发现故障，主站修改了，测试站需要修改，需要监督完成，比如：主站
所有故障问题，需要抄送给我，需要验证测试站是否右相同的问题，需要定期恢复。
２　开发站和测试站，有人修改了，环境被损坏了，需要责任人负责修复。
３　测试站未升级或测试未自动升级，对于此类问题需要严格把关，严格执行公
司流程。
４　项目中的任务，设计和开发前期有延误，拖到最后一天，自动部署测试站和
升级主站，需要明确升级计划和提交测试站的升级时间，对于特殊问题特殊处理。

*** 技术进步不大
作为技术开发人员，毫无疑问谁都想提高自己的技术实力，不断学习。
什么es hadoop spark 机器学习　大数据等等，都有很高的兴趣去学习。
可以和领导约定个目标，去实现技术进步。

*** 关于技术级别问题
专业能力　自完成　自设计
发现问题／解决问题 自完成　抓关键
创新能力　能完善　能优化
项目管理　会参与　带项目
知识传承  能升华　能推广
人才培养　寻指导　能解惑
    
*** 173ｍｑ　主站问题，邮件
问题描述：2015-12-11
发现主站　173主机，ｍｑ阻塞问题
问题处理过程：
１　检查研报datapool日志，未发现正常接收ｍｑ消息
２　保存现有进程环境，堆栈／日志／ｃｐｕ／内存信息，和运维沟通，重启服务
３　重启后仍然没有ｍｑ消息接收，检查日志发现重复订阅报错信息，
４　通过修改订阅主机信息，解决此问题
问题原因：
rpp datapool单主机173,存在重复的订阅,修改后解决此问题。
