* 总结
** 技术
*** 架构设计
*** 数据库
*** 业务设计
*** 算法
** 需求
*** 核心需求
** 团队
*** 梯队建设
*** 团队规范
*** ceo
*** 项目管理
** 干系人
** 赚钱创业
** 迭代赚钱的事情
*** 电子产品手工制作
1. esp32 水流控制器，手机控制抽水开关
2. esp32 桌面信息牌
3. esp32 语音聊天机器人，支持各个gpt模型
4. 银发团队科技
5. 软件开发架构写作
6. java算法
7. java架构知识
身上有什么东西可以卖出去呢
自己写文章
*** 投资自习室
选择房子，沟通房租价格
装修设计，房间设计特色，与别的自习室差异化
装修，消防设计？
打印机 下面铺个板子，否则不稳定
** mac book air 体验
1. 刚买到后，拆开包装，拿起这款电脑，直接被它的设计惊艳到了，简直就是一件艺术品，键盘背光灯，屏幕的清晰度，打开与盒盖的秒开体验，操作系统如此的丝滑流畅，让我切实感受到了乔布斯的伟大。
2. 我的需求主要是移动办公，来回带来带去的，要方便携带，对于性能要求不是很高，因为可以远程连接自己的服务器。还有更多的关注笔记本的续航，这个电脑续航确实很顶，可以让你随时随地打开和使用电脑，让你有了和纸质记事本相似的使用体验。总之这个笔记本让我觉得这个才是真正的笔记本电脑。
3. 平时用的比较多的功能有，苹果备忘录，加上苹果手机，备忘录功能相当给力，可以让你随时记录各种信息。命令行的类linux系统的体验，让你所想即所得。如果想操作windows可以使用MRD远程访问，体验也非常好。
** 迁移公文系统
目前迁移公文系统几个关键问题
1. 所有业务的功能迁移进度
2. 在线预览和编辑问题
3. 公文菜单跳转问题
4. OA目前日常问题维护
** eww 快捷键
  w  拷贝当前页面 URL    
  G     访问指定的url地址
  g  刷新当前页面
  q     退出
  l  后退    
  r  前进
  H     历史查看
  &     外部网页访问
  v  查看网页源码    
  b  添加当前网页到书签    
  B  查看书签    
  R  开启阅读模式    
  n/p  自动跳转到下一页/上一页    
  M-RET  在新 buffer 内打开链接    

** emacs 帮助相关
ctrl h ,m      mod模块帮助
ctrl h ,f/v/k 查询命令、变量、快捷键

** emacs搜索
project-find-name 搜索文件名
project-find-rgrep 搜索文件中的文本内容，linux和mac使用很爽

另外两个搜索
搜索参数定义
搜索所有函数引用

M-x xref-find-definitions：查找符号定义。
M-x xref-find-references：查找符号引用。

(global-set-key (kbd "C-c d") 'xref-find-definitions)  ;; 绑定到 C-c d
(global-set-key (kbd "C-c r") 'xref-find-references)   ;; 绑定到 C-c r


#+begin_src shell

  generate_tags.sh; shell脚本生成tags文件

  #!/bin/bash
  # 生成 TAGS 文件，支持多种语言
  find . \( -name "*.java" -o -name "*.js" -o -name "*.jsp" -o -name "*.html" -o -name "*.css" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.go" -o -name "*.py" -o -name "*.php" -o -name "*.sh" -o -name "*.yaml" -o -name "*.yml" \) -print | etags -
  echo "TAGS file generated successfully."


  chmod +x generate_tags.sh
  ./generate_tags.sh

  自动加载
  (setq tags-table-list '("~/project1/TAGS" "~/project2/TAGS"))

  加载：M-x visit-tags-table。
  查找定义：M-.。
  查找引用：M-x xref-find-references。

#+end_src

*** windows说明
windows系统文件使用gbk，emacs默认支持utf8
用字符串递归搜索文件内容时，会遭遇不确定的乱码问题，目前无法解决
换一种方式，使用“rg”的方式进行查询，它支持多种文件字符集格式的查找，
需要再验证下，是否可以解决windows中使用emacs进行文本查询的问题

注意，需要添加git的环境变量路径，因为它会使用习惯linux命令

*** 变量定义和函数定义的方法

*** emacs插件推荐
[[https://www.liuhaihua.cn/archives/221888.html][emacs推荐插件10个]] ctrl-c,ctrl-l 插件

*** emacs选择多行字符串，方便的方法
mac使用 ctrl shift 上下，直接就可以选择文本了，这个真方便

** emacs插件推荐ido和smex
ido是文件夹提示
smex是命令提示
这两个插件很方便
** 苹果切换中英文的两种方式
1. ctrl + 空格 两个键切换中英文
2. 左下角的两个contrl 一个键切换中英文

** 反思241228
1. 目标管理
带人一定要有目标，明确自己和团队的短中长期目标，比如年中，年终奖，优秀员工的评选，各自3个月，半年，三年的目标是什么，一定要有目标，不要埋头苦干，又是埋头苦干，明确下来。还有新人的培养目标，收买人心？
2. 感谢信2024发出来了
不是你自己觉得好就行，要别人觉得你优秀，
感觉最后做的不是很好，思考别人,获取人心，了解别人的好恶swot分析
周寒彬，不愿意与领导沟通，你去和上边说，就可以获取

** 未来计划20241219
本月创建自己的产品
1. 申请个体商户执照
2. 快速迭代打造一个老年人，宠物经济，涉及ai周边的产品
3. 通过直播方式对外进行营销，售卖

** 迁移公文系统
目前迁移公文系统几个关键问题
1. 所有业务的功能迁移进度
2. 在线预览和编辑问题
3. 公文菜单跳转问题
4. OA目前日常问题维护

本周工作
1. 督办系统，发送时提醒，规范化改造
2. 督办系统，wuhh两个问题
3. 信创菜单问题，优化改造

** 王猛
什么工作都行？不是，要有明确的目标
银行负责人每年都换，风水轮流转的趋势

** 2024已过去，2025新开始
*** 总结2024
埋头做事，苦干傻干，没有技巧
加班加点很多，不被看见，不被认可

*** 计划2025
目前信创切换已经没有难度，
oracle切换，全局思考
思考那些是重要的事情，做事要排优先级
遇事不是迎难而上，而是往后退缩
szw出事甩锅，银行新人糊涂蛋
每天思考，你的价值是什么，什么情况会被取代，会被开除，如何最大化自己的价值

** 创业与个体户创业
*** 申请个体户资格，准备材料
*** 养老的智能产品
功能点包括：
1. 每天天气预报
2. 每天新闻联播主要内容
3. 商店的门口来人告警

*** 视频直播进行销售
*** 低成本创业

** 最近更改的文件
